import 'user_model.dart';
import 'restaurant_model.dart';
import 'complaint_model.dart';
import 'inspection_model.dart';

class MockSeedData {
  static const List<UserModel> users = [
    UserModel(
      id: 'usr_001',
      name: 'User Account',
      email: 'user@example.com',
      phone: '+6012-3456789',
      role: UserRole.user,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=1',
    ),
    UserModel(
      id: 'adm_001',
      name: 'System Admin',
      email: 'admin@hygiene.gov.my',
      phone: '+6019-8765432',
      role: UserRole.admin,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=33',
    ),
    UserModel(
      id: 'gov_001',
      name: 'Health Officer (PIC)',
      email: 'officer.pic@hygiene.gov.my',
      phone: '+6017-1122334',
      role: UserRole.government,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
    ),
    UserModel(
      id: 'own_001',
      name: 'Restaurant Owner',
      email: 'owner@bistro.com',
      phone: '+6013-9988776',
      role: UserRole.owner,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=47',
    ),
  ];

  static const List<RestaurantModel> restaurants = [
    RestaurantModel(
      id: 'rst_101',
      name: 'Golden Dragon Noodle House',
      category: 'Chinese Noodle',
      address: '12 Jalan Petaling, City Centre, 50000 Kuala Lumpur',
      latitude: 3.1466,
      longitude: 101.6958,
      hygieneRiskScore: 12.5,
      riskCategory: RiskCategory.safe,
      status: RestaurantStatus.approved,
      violationCount: 0,
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600',
      lastUpdated: '2026-07-15',
    ),
    RestaurantModel(
      id: 'rst_102',
      name: 'Selera Kampung Bistro',
      category: 'Malay Local',
      address: '45 Jalan Alor, Bukit Bintang, 50200 Kuala Lumpur',
      latitude: 3.1478,
      longitude: 101.7100,
      hygieneRiskScore: 78.4,
      riskCategory: RiskCategory.high,
      status: RestaurantStatus.approved,
      violationCount: 4,
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600',
      lastUpdated: '2026-08-01',
    ),
    RestaurantModel(
      id: 'rst_103',
      name: 'Mamak Corner Curry House',
      category: 'Indian Mamak',
      address: '88 Jalan Imbi, 55100 Kuala Lumpur',
      latitude: 3.1420,
      longitude: 101.7130,
      hygieneRiskScore: 48.2,
      riskCategory: RiskCategory.moderate,
      status: RestaurantStatus.approved,
      violationCount: 2,
      imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?q=80&w=600',
      lastUpdated: '2026-06-20',
    ),
    RestaurantModel(
      id: 'rst_104',
      name: 'New Century Dim Sum',
      category: 'Dim Sum',
      address: '23 Jalan Sultan, 50000 Kuala Lumpur',
      latitude: 3.1440,
      longitude: 101.6980,
      hygieneRiskScore: 28.0,
      riskCategory: RiskCategory.safe,
      status: RestaurantStatus.pendingVerification,
      violationCount: 1,
      imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=600',
      lastUpdated: '2026-07-28',
    ),
    RestaurantModel(
      id: 'rst_105',
      name: 'Uncle Sam Burgers & Grill',
      category: 'Western Fast Food',
      address: '10 Jalan SS15/4D, 47500 Subang Jaya',
      latitude: 3.0760,
      longitude: 101.5880,
      hygieneRiskScore: 91.0,
      riskCategory: RiskCategory.high,
      status: RestaurantStatus.approved,
      violationCount: 6,
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=600',
      lastUpdated: '2026-08-04',
    ),
  ];

  static const List<ComplaintModel> complaints = [
    ComplaintModel(
      id: 'cmp_2026_001',
      restaurantId: 'rst_102',
      restaurantName: 'Selera Kampung Bistro',
      userId: 'usr_001',
      userName: 'User Account',
      category: 'Pest Infestation',
      issues: ['Cockroach near food storage', 'Uncovered trash bins'],
      description: 'Spotted a cockroach crawling near the cooked food trays around lunchtime.',
      status: ComplaintStatus.investigating,
      severity: SeverityLevel.high,
      latitude: 3.1478,
      longitude: 101.7100,
      isFlaggedForReview: false,
      submittedAt: '2026-08-04 13:20',
      photoUrls: ['https://picsum.photos/seed/pest1/300/200'],
    ),
    ComplaintModel(
      id: 'cmp_2026_002',
      restaurantId: 'rst_103',
      restaurantName: 'Mamak Corner Curry House',
      userId: 'usr_002',
      userName: 'User Account Two',
      category: 'Unclean Utensils',
      issues: ['Oily cups', 'Dirty cutlery with food residue'],
      description: 'Spoons and plates provided were not washed properly.',
      status: ComplaintStatus.pendingInspection,
      severity: SeverityLevel.medium,
      latitude: 3.1590,
      longitude: 101.7150,
      isFlaggedForReview: false,
      submittedAt: '2026-08-05 10:15',
      photoUrls: ['https://picsum.photos/seed/utensil/300/200'],
    ),
    ComplaintModel(
      id: 'cmp_2026_003',
      restaurantId: 'rst_102',
      restaurantName: 'Selera Kampung Bistro',
      userId: 'usr_002',
      userName: 'User Account Two',
      category: 'Food Poisoning Risk',
      issues: ['Expired meat ingredient', 'Foul odor from kitchen'],
      description: 'Chicken tasted sour and spoiled. High fever after eating.',
      status: ComplaintStatus.underReview,
      severity: SeverityLevel.high,
      latitude: 3.1600, // Mismatched GPS
      longitude: 101.7300,
      isFlaggedForReview: true,
      flaggedReason: 'GPS location mismatch (> 150m from restaurant)',
      submittedAt: '2026-08-06 08:30',
      photoUrls: ['https://picsum.photos/seed/spoiled/300/200'],
    ),
    ComplaintModel(
      id: 'cmp_2026_004',
      restaurantId: 'rst_105',
      restaurantName: 'Uncle Sam Burgers & Grill',
      userId: 'usr_001',
      userName: 'User Account',
      category: 'Poor Personal Hygiene',
      issues: ['No gloves/hairnets worn', 'Bare hands handling ready-to-eat food'],
      description: 'Staff handling burger patties without gloves while coughing.',
      status: ComplaintStatus.submitted,
      severity: SeverityLevel.medium,
      latitude: 3.0760,
      longitude: 101.5880,
      isFlaggedForReview: true,
      flaggedReason: 'Possible duplicate photo hash with cmp_2026_002',
      submittedAt: '2026-08-06 11:00',
      photoUrls: ['https://picsum.photos/seed/staff/300/200'],
    ),
    ComplaintModel(
      id: 'cmp_2026_005',
      restaurantId: 'rst_101',
      restaurantName: 'Golden Dragon Noodle House',
      userId: 'usr_001',
      userName: 'User Account',
      category: 'Waste Management',
      issues: ['Overflowing grease trap'],
      description: 'Grease trap leaking onto public walkway.',
      status: ComplaintStatus.resolved,
      severity: SeverityLevel.low,
      latitude: 3.1466,
      longitude: 101.6958,
      isFlaggedForReview: false,
      submittedAt: '2026-07-28 15:40',
      photoUrls: ['https://picsum.photos/seed/grease/300/200'],
    ),
  ];

  static const List<InspectionModel> inspections = [
    InspectionModel(
      id: 'insp_501',
      complaintId: 'cmp_2026_001',
      restaurantId: 'rst_102',
      restaurantName: 'Selera Kampung Bistro',
      scheduledDate: '2026-08-08 10:00 AM',
      conductedDate: '2026-08-06 02:00 PM',
      officerName: 'Health Officer (PIC)',
      outcome: InspectionOutcome.nonCompliant,
      findings: 'Multiple cockroaches found near flour sacks. Unclean floor drain.',
      recommendedAction: EnforcementType.closure,
      issuedAction: EnforcementType.closure,
      justification: 'Severe pest infestation poses immediate public health hazard.',
      fineAmount: 2500.0,
      enforcementStatus: EnforcementStatus.inProgress,
    ),
    InspectionModel(
      id: 'insp_502',
      complaintId: 'cmp_2026_002',
      restaurantId: 'rst_103',
      restaurantName: 'Mamak Corner Curry House',
      scheduledDate: '2026-08-09 11:30 AM',
      officerName: 'Health Officer (PIC)',
      outcome: InspectionOutcome.pending,
      findings: 'Inspection scheduled. Awaiting field site visit.',
      recommendedAction: EnforcementType.warning,
      issuedAction: EnforcementType.none,
      justification: '',
      fineAmount: 0.0,
      enforcementStatus: EnforcementStatus.pending,
    ),
  ];
}
