import 'user_model.dart';
import 'restaurant_model.dart';
import 'complaint_model.dart';
import 'inspection_model.dart';

class MockSeedData {
  static const List<UserModel> users = [
    UserModel(
      id: 'usr_001',
      name: 'User Account',
      email: 'user@example.com',
      phone: '+6012-3456789',
      role: UserRole.user,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=1',
    ),
    UserModel(
      id: 'adm_001',
      name: 'System Admin',
      email: 'admin@hygiene.gov.my',
      phone: '+6019-8765432',
      role: UserRole.admin,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=33',
    ),
    UserModel(
      id: 'gov_001',
      name: 'Health Officer (PIC)',
      email: 'officer.pic@hygiene.gov.my',
      phone: '+6017-1122334',
      role: UserRole.government,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
    ),
    UserModel(
      id: 'own_001',
      name: 'Businessman Account',
      email: 'owner@bistro.com',
      phone: '+6013-9988776',
      role: UserRole.owner,
      status: AccountStatus.active,
      avatarUrl: 'https://i.pravatar.cc/150?img=47',
    ),
  ];

  static List<RestaurantModel> restaurants = [
    const RestaurantModel(
      id: 'rest_001',
      name: 'Ocean Catch Seafood Restaurant',
      address: 'No. 12, Jalan Alor, Bukit Bintang, 50200 Kuala Lumpur',
      category: 'Seafood & Grill',
      latitude: 3.1466,
      longitude: 101.6958,
      hygieneRiskScore: 8.5,
      riskCategory: RiskCategory.safe,
      status: RestaurantStatus.approved,
      violationCount: 0,
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600',
      lastUpdated: '2026-08-10',
    ),
    const RestaurantModel(
      id: 'rest_002',
      name: 'Golden Dragon Bistro',
      address: 'Lot 45, Sungei Wang Plaza, Jalan Sultan Ismail, 50250 Kuala Lumpur',
      category: 'Chinese / Noodles',
      latitude: 3.1470,
      longitude: 101.7092,
      hygieneRiskScore: 18.2,
      riskCategory: RiskCategory.safe,
      status: RestaurantStatus.approved,
      violationCount: 1,
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600',
      lastUpdated: '2026-08-08',
    ),
    const RestaurantModel(
      id: 'rest_003',
      name: 'Mamaka Nasi Kandar',
      address: '28, Jalan Bangsar Utama 1, 59000 Kuala Lumpur',
      category: 'Malaysian / Indian',
      latitude: 3.1290,
      longitude: 101.6780,
      hygieneRiskScore: 38.5,
      riskCategory: RiskCategory.moderate,
      status: RestaurantStatus.approved,
      violationCount: 2,
      imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=600',
      lastUpdated: '2026-08-07',
    ),
    const RestaurantModel(
      id: 'rest_004',
      name: 'Subang Corner Food Stall',
      address: '14, Jalan SS 15/4D, 47500 Subang Jaya, Selangor',
      category: 'Hawker / Local',
      latitude: 3.0760,
      longitude: 101.5890,
      hygieneRiskScore: 74.0,
      riskCategory: RiskCategory.high,
      status: RestaurantStatus.approved,
      violationCount: 4,
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=600',
      lastUpdated: '2026-08-05',
    ),
    const RestaurantModel(
      id: 'rest_005',
      name: 'Zen Sushi & Teppanyaki',
      address: 'Level 3, Pavilion KL, Bukit Bintang, 55100 Kuala Lumpur',
      category: 'Japanese',
      latitude: 3.1488,
      longitude: 101.7133,
      hygieneRiskScore: 2.1,
      riskCategory: RiskCategory.safe,
      status: RestaurantStatus.approved,
      violationCount: 0,
      imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=600',
      lastUpdated: '2026-08-11',
    ),
  ];
  static List<ComplaintModel> complaints = [
    const ComplaintModel(
      id: 'cmp_2026_001',
      restaurantId: 'rest_001',
      restaurantName: 'Ocean Catch Seafood Restaurant',
      userId: 'usr_001',
      userName: 'Ahmad Abdullah',
      category: 'Food Safety',
      issues: ['Dirty Kitchen Counters', 'Flies Near Food Display'],
      description: 'Foreign object found in fried rice. Observed dirty food preparation counters and flies near food display.',
      status: ComplaintStatus.underReview,
      severity: SeverityLevel.high,
      latitude: 3.1466,
      longitude: 101.6958,
      isFlaggedForReview: true,
      flaggedReason: 'Duplicate Image Match Detected (cmp_2026_002)',
      submittedAt: '2026-08-10',
      photoUrls: [],
    ),
    const ComplaintModel(
      id: 'cmp_2026_002',
      restaurantId: 'rest_002',
      restaurantName: 'Golden Dragon Bistro',
      userId: 'usr_002',
      userName: 'Siti Sarah',
      category: 'Hygiene & Cleanliness',
      issues: ['Unwashed Utensils', 'Staff Sanitation'],
      description: 'Poor food hygiene and unwashed utensils used during peak dining hours.',
      status: ComplaintStatus.investigating,
      severity: SeverityLevel.medium,
      latitude: 3.1500,
      longitude: 101.7000,
      isFlaggedForReview: false,
      submittedAt: '2026-08-08',
      photoUrls: [],
    ),
    const ComplaintModel(
      id: 'cmp_2026_003',
      restaurantId: 'rest_003',
      restaurantName: 'Mamaka Nasi Kandar',
      userId: 'usr_003',
      userName: 'Tan Ah Kow',
      category: 'Pest Control',
      issues: ['Pest Infestation'],
      description: 'Cockroach seen crawling near the ice machine and storage containers.',
      status: ComplaintStatus.pendingInspection,
      severity: SeverityLevel.high,
      latitude: 3.1400,
      longitude: 101.6900,
      isFlaggedForReview: true,
      flaggedReason: 'High AI Anomaly & GPS Mismatch',
      submittedAt: '2026-08-07',
      photoUrls: [],
    ),
    const ComplaintModel(
      id: 'cmp_2026_004',
      restaurantId: 'rest_001',
      restaurantName: 'Ocean Catch Seafood Restaurant',
      userId: 'usr_004',
      userName: 'Ramasamy',
      category: 'Food Safety',
      issues: ['Expired Food'],
      description: 'Expired dairy products stored in refrigerator alongside raw chicken.',
      status: ComplaintStatus.submitted,
      severity: SeverityLevel.medium,
      latitude: 3.1466,
      longitude: 101.6958,
      isFlaggedForReview: true,
      flaggedReason: 'Image Hash Duplicate Flagged',
      submittedAt: '2026-08-11',
      photoUrls: [],
    ),
  ];

  static List<InspectionModel> inspections = [
    const InspectionModel(
      id: 'insp_2026_001',
      complaintId: 'cmp_2026_001',
      restaurantId: 'rest_001',
      restaurantName: 'Ocean Catch Seafood Restaurant',
      scheduledDate: '2026-08-11',
      conductedDate: '2026-08-11',
      officerName: 'Health Officer (PIC)',
      outcome: InspectionOutcome.nonCompliant,
      findings: 'Heavy grease buildup on kitchen grease traps, cross-contamination risks identified near prep stations.',
      recommendedAction: EnforcementType.warning,
      issuedAction: EnforcementType.warning,
      justification: 'Failure to maintain baseline sanitation guidelines under Act 777.',
      fineAmount: 500.0,
      enforcementStatus: EnforcementStatus.inProgress,
    ),
  ];
}
